config:
  mapbox:
    apikey: "pk.eyJ1IjoiZnBhc3Nhbml0aSIsImEiOiIxNTg3MGRlZWQyNjVkZjExMGVlNWVjNDFjOWQyNzNiMiJ9.pYKDlO4v-SNiDz08G9ZZoQ"

    # default map location (center of the map, and zoom level)
    init:
      zoom: 10
      center: [2.374126, 51.023950]

    geocoder:
      # Narrow search results to the defined boundingbox to avoid to many noises
      searchbbox: [2.108065,50.896051,2.608629,51.132778]

  data:
    datasetid: ""
    domainid: ""
